version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 10
    labels:
      - 'type: dependencies'
      - 'type: automerge'
    allow:
      - dependency-type: direct
