name: Test Regenerate on PR
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  regenerate_and_test:
    uses: ./.github/workflows/regenerate.yml
