name: Test Regenerate on PR
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  regenerate_and_test:
    if: ${{ github.ref != 'refs/heads/main' }}
    name: Test regenerate nix package index
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name:  Nix packages
        uses: ahobson/cache-install@adh-nix-version-v4
        with:
          key: nix-${{ hashFiles('nix/default.nix') }}
          nix_file: 'nix/default.nix'
          nix_version: https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz

      - name: npm yarn cache directory path
        id: npm-cache-dir-path
        run: echo "npm-cache-dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.npm-cache-dir }}/_cacache
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install npm packages
        run: |
          npm ci

      # see https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
      - name: Checkout nixpkgs
        run: >-
          mkdir -p nixpkgs-cache &&
          cd nixpkgs-cache &&
          test -d nixpkgs ||
          git clone --filter=tree:0 --single-branch --branch=nixpkgs-unstable https://github.com/NixOS/nixpkgs.git

      - name: Run Regenerate
        run: |
          ./node_modules/.bin/tsx bin/regenerate.ts
        env:
          NIXPKGS_DIR: nixpkgs-cache/nixpkgs

      - name: Test build
        run: |
          npm test && VITE_GITHUB_SHA="${GITHUB_SHA}" npm run build
