name: Regenerate
on:
  workflow_call:

jobs:
  regenerate:
    name: regenerate nix package index
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name:  Nix packages
        uses: ahobson/cache-install@adh-nix-version-v4
        with:
          # update the key when the nix_install_url changes
          key: nix-${{ hashFiles('nix/default.nix') }}-2.23.4
          nix_file: 'nix/default.nix'
          nix_version: https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
          # update the key when the nix_install_url changes
          nix_install_url: https://releases.nixos.org/nix/nix-2.23.4/install

      - name: npm yarn cache directory path
        id: npm-cache-dir-path
        run: echo "npm-cache-dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.npm-cache-dir }}/_cacache
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install npm packages
        run: |
          npm ci

      # see https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
      - name: Checkout nixpkgs
        run: >-
          mkdir -p nixpkgs-cache &&
          cd nixpkgs-cache &&
          test -d nixpkgs ||
          git clone --filter=tree:0 --single-branch --branch=nixpkgs-unstable https://github.com/NixOS/nixpkgs.git

      - name: Run Regenerate
        run: |
          nix-env --version
          curl -sSfL -O https://ahobson.github.io/nix-package-search/nix/nixpkgs-unstable/all_packages.csv
          curl -sSfL -O https://ahobson.github.io/nix-package-search/nix/nixpkgs-unstable/last_seen.txt
          mv all_packages.csv last_seen.txt public/nix/nixpkgs-unstable
          ./node_modules/.bin/tsx bin/regenerate.ts
          mv public/nix/nixpkgs-unstable/all_packages.sqlite3 public/nix/nixpkgs-unstable/all_packages.sqlite30
          ln -s all_packages.sqlite30 public/nix/nixpkgs-unstable/all_packages.sqlite3
        env:
          NIXPKGS_DIR: nixpkgs-cache/nixpkgs

      - name: Run Test
        run: |
          npm test

      - name: Run build
        run: |
          VITE_GITHUB_SHA="${GITHUB_SHA}" npm run build

      - name: Setup Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'dist'
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@v4


